// Read-only evidence and rehearsal views. No score is invented from missing data.
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp = value => Number.isFinite(value) ? `${value.toFixed(2)}s` : '未确认';
const actions={shot:'出手',pass:'传球',movement:'跑动',screen:'掩护',result:'结果',rebound:'篮板',defense:'防守'};
const status = {pass:'通过',fail:'待处理',unknown:'未验证'};

export function renderProductionDesk({report, tab='vision', selected=null, frames=[], loading=false, error=null, loop=null}) {
  const menu=[['vision','画面核对'],['voice','解说节奏'],['delivery','提交检查']].map(([key,label])=>
    `<button type="button" data-action="desk-tab" data-tab="${key}" aria-selected="${key===tab}" class="${key===tab?'active':''}">${label}</button>`).join('');
  const header=`<div class="desk-header"><nav role="tablist" aria-label="制作检查">${menu}</nav><button type="button" data-action="refresh-preflight" class="button quiet small">${loading?'检查中…':'更新检查'}</button></div>`;
  let body='';
  if(tab==='vision') {
    const refs=new Set(selected?.frameIds||[]), cited=frames.filter(f=>refs.has(f.id));
    body=`<div class="review-focus"><div><span class="eyebrow">${selected?'当前事件':'画面证据'}</span><h3>${esc(selected?.description||'选择一条事件，核对对应画面。')}</h3>${selected?`<div class="review-transport"><button type="button" class="button secondary small" data-action="loop-observation" data-id="${esc(selected.id)}" aria-pressed="${loop?.id===selected.id}">${loop?.id===selected.id?'停止循环':'循环回看'}</button><button type="button" class="button quiet small" data-action="evidence-window" data-id="${esc(selected.id)}">提取前后画面</button><span>${stamp(selected.start)}—${stamp(selected.end)}</span></div><div class="review-facts"><span>人物 <b>${selected.playerIds?.length?'有名单身份，须核对':'尚未确认姓名'}</b></span><span>动作 <b>${esc(actions[selected.type]||'观察')}</b></span><span>复核 <b>${esc(selected.review?.status==='accepted'?'已确认':selected.review?.status==='rejected'?'已排除':'待确认')}</b></span></div>`:''}</div><div class="review-frame-pair">${cited.slice(0,4).map(f=>`<button type="button" data-action="seek-frame" data-time="${f.actualTime}"><img src="${esc(f.url)}" alt="事件引用的真实画面 ${stamp(f.actualTime)}"><span>${stamp(f.actualTime)}</span></button>`).join('')||'<p>此事件还没有可展示的引用帧。</p>'}</div></div>`;
    const queue=report?.vision?.reviewQueue||[];
    if(queue.length)body+=`<div class="desk-queue"><h4>待核对事项 <span>${queue.length}</span></h4>${queue.slice(0,12).map(q=>`<div class="desk-issue"><span class="issue-dot"></span><p>${esc(q.message||q.reason||q.code)}${q.observationId?` <button type="button" data-action="select-observation" data-id="${esc(q.observationId)}">打开事件</button>`:''}</p></div>`).join('')}</div>`;
    const windows=report?.vision?.reinspectionWindows||[];
    if(windows.length)body+=`<div class="inspection-windows"><h4>建议补看的片段</h4>${windows.map(w=>`<button type="button" class="button quiet small" data-action="inspect-window" data-start="${w.start}" data-end="${w.end}">${stamp(w.start)}—${stamp(w.end)}</button>`).join('')}</div>`;
    if(report)body+=`<p class="desk-footnote">${report.vision?.automaticAcceptance===false?'检查结果用于复核；不会自动确认人物、进球或战术。':''}</p>`;
  } else if(tab==='voice') {
    const rehearsal=report?.rehearsal;
    body=rehearsal?.beats?.length?`<div class="voice-score">${rehearsal.beats.map(b=>`<article><div class="voice-score-head"><button type="button" data-action="seek-voice-cue" data-id="${esc(b.beatId)}">${stamp(b.cue.sourceStart)}—${stamp(b.cue.sourceEnd)} ↗</button><span>${b.measuredAudio?.reportMatchesStory?'音频实测':'文字估时'}</span></div><p>${esc(b.text)}</p><div class="voice-budget"><span>窗口 <strong>${Number.isFinite(b.cue.availableSeconds)?b.cue.availableSeconds.toFixed(2):'待确认'}s</strong></span><span>${b.measuredAudio?.reportMatchesStory?'语音实长':'预计语音'} <strong>${stamp(b.measuredAudio?.reportMatchesStory?b.measuredAudio.speechDuration:b.estimate?.complete===false?null:b.estimate?.durationSeconds)}</strong></span><span>${b.estimate?.complete===false?'先核对指标':b.estimate?.fitsAtMaxTempo?'建议试听':'建议缩短句子'}</span></div>${b.glossary?.length?`<small>${b.glossary.map(x=>esc(x.terms?.[rehearsal.language]||x.label||x.term||x.id)).join(' · ')}</small>`:''}</article>`).join('')}</div>${(rehearsal.issues||[]).map(i=>`<div class="desk-issue"><span class="issue-dot"></span><p>${esc(i.message)}</p></div>`).join('')}<p class="desk-footnote">文字估时仅供编稿参考。最终按真实音频测时；最多加速至 1.15 倍，超窗须修改文案。</p>`:'<p class="desk-empty">编排解说后，可在这里检查逐句节奏与术语。</p>';
  } else {
    body=report?`<div class="delivery-grid">${report.checks.map(c=>`<div class="delivery-check ${esc(c.status)}"><span class="check-icon">${c.status==='pass'?'✓':c.status==='fail'?'!':'○'}</span><div><strong>${esc(c.label)}</strong><p>${esc(c.detail)}</p></div><small>${status[c.status]||'未验证'}</small></div>`).join('')}</div><div class="desk-download"><button type="button" class="button secondary small" data-action="download-preflight">下载检查报告</button><span>依据当前保存的项目</span></div>`:'<p class="desk-empty">点击更新检查，查看当前项目与交付缺项。</p>';
  }
  return `<section class="production-desk" aria-label="制作检查工作台">${header}${error?`<p class="desk-footnote error">${esc(error)}，可点击更新检查重试。</p>`:''}${body}</section>`;
}

export function renderClockTool(frames, preview=null) {
  const options=frames.map(f=>`<option value="${esc(f.id)}">${stamp(f.actualTime)} · ${esc(f.id.slice(0,6))}</option>`).join('');
  return `<section class="panel-section clock-tool"><h3>比赛时钟 → 视频时间</h3><p class="help-text">在同一连续原速镜头选两张源帧，填写比分牌倒计时。暂停和回放需分段。</p><form data-form="clock-preview"><div class="field-row"><label class="field"><span>镜头段</span><input name="clockSegment" required maxlength="80" placeholder="segment-1"></label><label class="field"><span>节次</span><input name="clockPeriod" type="number" min="1" max="20" value="1" required></label></div><label class="field"><span>目标比赛时钟</span><input name="targetClock" required placeholder="07:41"></label>${[1,2].map(n=>`<div class="field-row"><label class="field"><span>锚点 ${n} · 源帧</span><select name="anchorFrame${n}" required><option value="">选择已保存画面</option>${options}</select></label><label class="field"><span>比分牌时钟</span><input name="anchorClock${n}" required placeholder="07:42"></label></div>`).join('')}<button class="button secondary full" type="submit" ${frames.length<2?'disabled':''}>预览映射</button></form>${preview?`<div class="clock-result"><strong>源片 ${stamp(preview.mapping.videoTime)}</strong><p>读数不确定度约 ±${Number(preview.uncertaintySeconds).toFixed(2)} 秒。请回看画面，再确认事件。</p><button type="button" class="button quiet small" data-action="seek-frame" data-time="${preview.mapping.videoTime}">回看片段</button><p class="help-text">该映射可用于下方事件绑定，未自动修改任何指标。</p></div>`:''}</section>`;
}

export function renderMetricIntake(source=null, result=null) {
  const fields=[['recordId','记录 ID'],['metricId','指标 ID'],['value','指标数值'],['eventId','事件 ID'],['shotId','出手 ID'],['playerId','球员 ID'],['observedAt','发生时间'],['availableAt','可用时间'],['unit','单位'],['validFrom','生效时间'],['validTo','结束时间'],['gameId','比赛 ID'],['teamId','球队 ID'],['seasonId','赛季 ID'],['period','节次'],['segmentId','镜头段']];
  const rows=source?fields.map(([key,label])=>`<label class="field"><span>${label}</span><select name="map-${key}"><option value="">未提供</option>${source.columns.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label>`).join(''):'';
  return `<section class="panel-section metric-intake"><h3>原始指标文件</h3><p class="help-text">先查看原始列，再按数据说明选择字段。单位和口径以提供者字典为准。</p><form data-form="metric-source"><label class="field"><span>CSV / JSON 数据行</span><input name="metricSourceFile" type="file" accept=".csv,.json" required></label><button class="button secondary full" type="submit">查看字段</button></form>${source?`<form data-form="metric-preview"><p class="help-text">${source.rowCount} 行 · ${source.columns.length} 列</p><label class="field"><span>提供者指标字典 JSON</span><input name="metricDictionary" type="file" accept=".json" required></label><div class="field-row"><label class="field"><span>粒度</span><select name="metricGranularity"><option value="shot">单次出手</option><option value="event">单次事件</option></select></label><label class="field"><span>时间基准</span><select name="metricTimeBase"><option value="video">源片秒数</option><option value="game-clock">比赛倒计时</option></select></label></div><div class="metric-field-grid">${rows}</div><button class="button secondary full" type="submit">预览转换</button></form>`:''}${result?`<div class="metric-preview-result"><h4>接受 ${result.counts?.accepted||0} 行 · 排除 ${result.counts?.rejected||0} 行</h4>${result.rejectedRows.slice(0,10).map(r=>`<p class="help-text">行 ${r.rowNumber} · ${esc(r.message)}</p>`).join('')}${result.validation?.error?`<p class="help-text">${esc(result.validation.error.message||result.validation.error)}</p>`:''}<p class="help-text">缺失值与未知可用时间保持为空。确认导入会清除旧事件绑定、解说和审核，需要重新编排。</p><button class="button secondary small" type="button" data-action="download-metric-preview">下载预览</button> <button class="button small" type="button" data-action="confirm-metric-preview" ${result.bundle&&result.validation?.ok&&result.counts?.accepted>0&&result.status!=='blocked'?'':'disabled'}>确认导入接受的记录</button></div>`:''}</section>`;
}
